/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dota.pkg3;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author erickbassett
 */
public class CombatPanel extends javax.swing.JPanel {

    /**
     * Creates new form CombatPanel
     */
    
    public CombatPanel() {
        initComponents();
        initData();
    }
    
//    private ArrayList<Attack> moves;
    private Enemy enemy;
//    private ArrayList<Attack> enemyMoves;
    private Character character;
    
    
    private void initData(){
//        this.character = new Character(this.character.getHealth(), this.character.getAttacks(), this.character.getImage());
        
        
//        this.character.moves.add(new Attack("Flame", 10, 30, .5));
        hideAttacks();
//        this.setEnemy(new Enemy("Bob", 100, enemyMoves, ResourceTools.loadImageFromResource("Resources/front_idle.png")));
//        enemyMoves = new ArrayList<Attack>();
//        enemyMoves.add(new Attack("Bite", 10, 15, 1));
//        this.getEnemy().setAttacks(enemyMoves);
//        jlblEnemyHealth.setText(String.valueOf(this.getEnemy().getHealth()));
//        jlblYourHealth.setText(String.valueOf(character.getHealth()));
//        jlblEnemyImage.setIcon(new ImageIcon(ResourceTools.loadImageFromResource("Resources/front_idle.png")));
    }
    
    
    
    
    private void hideAttacks(){
       this.jPanel1.setVisible(true);
       this.jPanel2.setVisible(false); 
    }
    
    private void displayAttacks(){  
        this.jPanel1.setVisible(false);
        this.jPanel2.setVisible(true);
        if (this.character.getAttacks() != null){
            DefaultListModel listModel = new DefaultListModel();
            
            for(Attack attack : this.character.getAttacks()){
                listModel.addElement(attack.getDisplay());
            }
            this.jList1.setModel(listModel);
        }
    }
    
    private void processAttack(){
        if (jList1.getSelectedIndex() != -1){
            int friendlyDamage = this.character.getAttacks().get(jList1.getSelectedIndex()).attack(this.character.getAttacks().get(jList1.getSelectedIndex()));
            if (friendlyDamage != -1){
                this.getEnemy().setHealth(this.getEnemy().getHealth() - friendlyDamage);
            jlblEnemyHealth.setText(String.valueOf(this.getEnemy().getHealth()));
            } else {
                System.out.println("miss!");
            }
            int enemyAttack = this.getEnemy().randomAttack();
            System.out.println("enemy attack:" + enemyAttack);
            int enemyDamage = this.getEnemy().getAttacks().get(enemyAttack).attack(this.enemy.getAttack(enemyAttack));
            if (enemyDamage != -1){
            this.character.setHealth(this.character.getHealth() - enemyDamage);
            jlblYourHealth.setText(String.valueOf(this.character.getHealth()));
            } else {
                System.out.println("enemy miss!");
            }
            
//            System.out.printf("Selected attack = #%d %s\n",jList1.getSelectedIndex(), jList1.getSelectedValue().toString());
//            System.out.printf("Look up attack as %s\n", this.moves.get(jList1.getSelectedIndex()).getDisplay());
        }  
    }
    
    
    
    
    public void setEnemyName(String enemyName) {
        this.jlblEnemyName.setText(enemyName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblEnemyName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnMove = new javax.swing.JButton();
        jbtnItem = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnAttack = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jlistMoves = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jlblEnemyImage = new javax.swing.JLabel();
        jlblEnemyHealth = new javax.swing.JLabel();
        jlblYourHealth = new javax.swing.JLabel();

        jlblEnemyName.setText("jLabel1");

        jbtnMove.setText("Moves");
        jbtnMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMoveActionPerformed(evt);
            }
        });

        jbtnItem.setText("Item");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jbtnItem)
            .add(jButton3)
            .add(jButton4)
            .add(jbtnMove)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jbtnMove)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(jbtnItem)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .addContainerGap())
        );

        jbtnAttack.setText("Attack");
        jbtnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAttackActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jlistMoves.setViewportView(jList1);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jbtnAttack)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbtnCancel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jlistMoves, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jlistMoves, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnAttack)
                    .add(jbtnCancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlblYourHealth.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(54, 54, 54)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(195, 195, 195)
                                .add(jlblEnemyImage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jlblEnemyName)
                        .add(71, 71, 71)
                        .add(jlblEnemyHealth)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jlblYourHealth)))
                .add(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblEnemyName)
                    .add(jlblEnemyHealth)
                    .add(jlblYourHealth))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE)
                .add(jlblEnemyImage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMoveActionPerformed
        displayAttacks();
    }//GEN-LAST:event_jbtnMoveActionPerformed

    private void jbtnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAttackActionPerformed
        processAttack();
        hideAttacks();
    }//GEN-LAST:event_jbtnAttackActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        hideAttacks();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnAttack;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnItem;
    private javax.swing.JButton jbtnMove;
    private javax.swing.JLabel jlblEnemyHealth;
    private javax.swing.JLabel jlblEnemyImage;
    private javax.swing.JLabel jlblEnemyName;
    private javax.swing.JLabel jlblYourHealth;
    private javax.swing.JScrollPane jlistMoves;
    // End of variables declaration//GEN-END:variables
/**
     * @return the character
     */
    public Character getCharacter() {
        return character;
    }

    /**
     * @param character the character to set
     */
    public void setCharacter(Character character) {
        this.character = character;
        jlblYourHealth.setText(String.valueOf(character.getHealth()));
    }

    /**
     * @return the enemy
     */
    public Enemy getEnemy() {
        return enemy;
    }

    /**
     * @param enemy the enemy to set
     */
    public void setEnemy(Enemy enemy) {
        this.enemy = enemy;
        jlblEnemyHealth.setText(String.valueOf(this.getEnemy().getHealth()));
        jlblEnemyImage.setIcon(new ImageIcon(this.enemy.getEnemyImage()));
    }

    
    
}
